version: '3.8'

networks:
  ez-apps-network:
    name: ez-apps-network
    driver: bridge

services:
  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    #restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-service
    ports:
      - "25431:5432"
    networks:
      - ez-apps-network
    volumes:
      - user_service_data:/var/lib/postgresql/data

  task-service-db:
    image: postgres:latest
    container_name: task-service-db
    #restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task-service
    ports:
      - "25432:5432"
    networks:
      - ez-apps-network
    volumes:
      - task_service_data:/var/lib/postgresql/data

volumes:
  user_service_data:
  task_service_data:
