version: '3.8'

networks:
  eztalo-network:
    name: eztalo-network
    driver: bridge

services:
  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    #restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-service
    ports:
      - "25431:5432"
    networks:
      - eztalo-network
    volumes:
      - user_service_data:/var/lib/postgresql/data

  task-service-db:
    image: postgres:latest
    container_name: task-service-db
    #restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task-service
    ports:
      - "25432:5432"
    networks:
      - eztalo-network
    volumes:
      - task_service_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - eztalo-network

volumes:
  user_service_data:
  task_service_data:
  vault-data:
    driver: local
  loki-data:
  grafana-storage:
  redis-data: