name: Build and Push Docker Image of User Service

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to build from'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Docker tag
        id: vars
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          TAG="${{ github.event.inputs.branch }}-$SHORT_SHA"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -f ezapps-user-api.dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/ezapps-user-service:${{ env.TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/ezapps-user-service:latest .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ezapps-user-service:${{ env.TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ezapps-user-service:latest
