name: Build and Push Docker Image of local FE

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to build from'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Create .env file
        run: |
          cat <<EOF > .env
          VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_TASK_SERVICE_URL=${{ secrets.VITE_TASK_SERVICE_LOCAL_URL }}
          VITE_USER_SERVICE_URL=${{ secrets.VITE_USER_SERVICE_LOCAL_URL }}
          EOF

      - name: Set Docker tag
        run: |
          echo "TAG=${{ github.event.inputs.branch }}-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -f ezapps-fe.dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/ezapps-local-fe:${{ env.TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/ezapps-local-fe:latest .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ezapps-local-fe:${{ env.TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ezapps-local-fe:latest
